---
- name: Validate nftables config
  ansible.builtin.command:
    cmd: nft -f /etc/nftables.conf -c

- name: Restart nftables
  ansible.builtin.systemd_service:
    name: nftables
    enabled: true
    state: restarted
    daemon_reload: true

