---
- name: Validate chrony config
  ansible.builtin.command:
    cmd: chronyd -p

- name: Restart chrony
  ansible.builtin.systemd_service:
    name: chrony
    enabled: true
    state: restarted
    daemon_reload: true

