---
- name: Create /etc/systemd/system/chrony.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/chrony.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create /etc/systemd/system/chrony.service.d/override.conf
  ansible.builtin.copy:
    content: "{{ chrony_systemd_override }}"
    dest: /etc/systemd/system/chrony.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart chrony
