---
- name: Install systemd-resolved
  ansible.builtin.apt:
    name: systemd-resolved
    state: present
    install_recommends: false
    update_cache: true

- name: Include tasks to configure systemd-resolved
  ansible.builtin.include_tasks: conf.yml
  when: systemd_resolved is defined

- name: Flush handlers
  ansible.builtin.meta: flush_handlers